### PR TITLE
feat: implement design refresh

### PR DESCRIPTION
**Pull request by BlueSlug**
* [x] This pull request has been linted by running `npm run lint` without errors
* [x] This pull request has been tested by running `npm run start` and reviewing affected routes
* [x] This pull request has been built by running `npm run build` without errors
* [x] This isn't a duplicate of an existing pull request

## Description

Implements new design updates including full-width video on the home page, a "Subscribe" button in the footer and new navigation styling.

## Steps to test

1. Verify the styling updates are present and look acceptable
2. Test the home page embedded YouTube video at a variety of screen widths to ensure it stays full-width at all times*
3. Verify the Subscribe button is present at the top of the footer and working properly

_*below viewport widths of approximately 250 pixels, things start to get weird for all site content, not just the video._

## Additional information

This PR also solves an issue which caused the build script to fail in PowerShell.

## Related issues

Some issues are introduced or represent incomplete work from this PR:
- #649
- #651
- #652

### CODE REVIEW

**Comment by cindyli** [comment]
As the border of the search box on the navigation bar remains grey, it becomes invisible or barely visible when a contrast theme is selected.

search-box-border

**Comment by cindyli** [comment]
The border of "click to subscribe" button disappears when a contrast theme is selected.

subscribe-button-border

**Comment by cindyli** [comment]
When setting the UIO "text style" to "open dyslexic" and turn on "enhance input", the style of "click to subscribe" button is broken. This only happens when the "text style" is set to "Verdana".

subscribe-button-on-large-font

**Comment by cindyli** [comment]
The text color of the logo (We Count) at the top left corner is using `$navy-dark`. In the new design, it should be in black too. This seems the only spot that `$navy-dark` is used. Once it's changed to black, the definition of `$navy-dark` can be removed.

**Comment by BlueSlug** [comment]
> With "iphone 5/SE" mobile view, when setting the UIO "text style" to "open dyslexic" and turning on "enhance input", the style of "click to subscribe" button is broken. This also happens when the "text style" is set to "Verdana".
> 
> subscribe-button-on-large-font

This one is proving tricky to solve quickly. Wrapping the `a` in a `div` will address the awkward text-wrapping, but it introduces some CSS issues with the hover and focus states.

**Comment by cindyli** [comment]
> > With "iphone 5/SE" mobile view, when setting the UIO "text style" to "open dyslexic" and turning on "enhance input", the style of "click to subscribe" button is broken. This also happens when the "text style" is set to "Verdana".
> > subscribe-button-on-large-font
> 
> This one is proving tricky to solve quickly. Wrapping the `a` in a `div` will address the awkward text-wrapping, but it introduces some CSS issues with the hover and focus states.

Reducing the padding of this `a` link on smaller screens is an easy way to fix this problem.

**Comment by BlueSlug** [comment]
> > > With "iphone 5/SE" mobile view, when setting the UIO "text style" to "open dyslexic" and turning on "enhance input", the style of "click to subscribe" button is broken. This also happens when the "text style" is set to "Verdana".
> > > subscribe-button-on-large-font
> > 
> > 
> > This one is proving tricky to solve quickly. Wrapping the `a` in a `div` will address the awkward text-wrapping, but it introduces some CSS issues with the hover and focus states.
> 
> Reducing the padding of this `a` link on smaller screens is an easy way to fix this problem.

That works too :) I was trying to do it in a way that preserved the appearance, but your suggestion is easier and frees up more screen real estate. I'll give it a shot :)

**Pull request merged**
