### PR TITLE
added the border to the elements of navbar

### PR DESCRIPTION
**Pull request by Raunaksingh100**
* [x] This pull request has been linted by running `npm run lint` without errors
* [x] This pull request has been tested by running `npm run start` and reviewing affected routes
* [x] This pull request has been built by running `npm run build` without errors
* [x] This isn't a duplicate of an existing pull request

## Description

added the border radius to the elements of navbar while hovar
see in the screenshot given below for the better understanding.......

## Steps to test

1. go to the wecount website
2.  over on the elements of the navbar

### screenshot before --
now ft

after---
now

## Related issues
#351 

@cindyli  plz  view this pr

### CODE REVIEW

**Comment by cindyli** [comment]
Not desired in the wireframe.

**Comment by Raunaksingh100** [comment]
> Not desired in the wireframe.
@cindyli 
is this sample you are making and can you provide me the gitter grp or any other grp of this orgainsiation..
sample

**Comment by cindyli** [comment]
Yes, this is the wireframe. Our team doesn't use Gitter. For accessibility concerns, IRC is the main channel we use to communicate.

**Comment by Raunaksingh100** [comment]
@cindyli  can you provide the direct link of irc channel.....

**Comment by jobara** [comment]
@Raunaksingh100 please read the [IRC Channel wiki page](https://wiki.fluidproject.org/display/fluid/IRC+Channel). The information for getting connected is outlined there. You should join the #fluid-work room.

**Comment by Raunaksingh100** [comment]
> > Not desired in the wireframe.
> > @cindyli
> > is this sample you are making and can you provide me the gitter grp or any other grp of this orgainsiation..
> > sample
> 
> ###i found this img from here link
> https://www.figma.com/file/0lcLol3X5MmOXackT2YbHJ/WeCount-website?node-id=0%3A1

accrording to this we need to add tools and our data in navbar then serve a html page in when we click on that

**Comment by Raunaksingh100** [comment]
> @Raunaksingh100 please read the [IRC Channel wiki page](https://wiki.fluidproject.org/display/fluid/IRC+Channel). The information for getting connected is outlined there. You should join the #fluid-work room.

this is irc channel plx help
irccc

**Comment by jobara** [comment]
@Raunaksingh100 I'm not sure what you need help with exactly, but you don't need to specify a password if you haven't registered your nickname.

**Pull request closed without merging**
