### PR TITLE
fix: use box shadow instead of border on tags (resolves #316)

### LINKED ISSUE #316: Use box-shadow instead of border on tags
## Is your feature request related to a problem? Please describe.

Other links and buttons on the website are using box-shadow to style the outline. Changing tag outlines from border to box-shadow makes the uio tag hover/focus style look better and is more consistent with the outline styling in the rest of the website. As of now the uio hover/focus styling on tags look like its over lapping as shown in the attached image in the Additional context section.

## Describe the solution you'd like

Replace `border` with `box-shadow` for the tags on the site.

## Describe alternatives you've considered

N/A

## Additional context

Screen Shot 2020-06-30 at 4 41 16 PM

### PR DESCRIPTION
**Pull request by TeddTech**
* [x] This pull request has been linted by running `npm run lint` without errors
* [x] This pull request has been tested by running `npm run start` and reviewing affected routes
* [x] This pull request has been built by running `npm run build` without errors
* [x] This isn't a duplicate of an existing pull request

## Description
Replaced `border` with `box-shadow` for tags.

## Steps to test

1. Go to deploy preview
2. Go to views page then navigate to a post with tags at the bottom. (For example "The Importance of Peripheral Vision")
3. Turn on uio contrast themes (white foreground/black background would be best, this is uio contrast theme option number 2)
4. Hover/focus over the tags and confirm they no longer look like they're overlapping

**Expected behavior:** 

No overlapping of the outline should occur while hovering/focusing on tags.

## Additional information

N/A

## Related issues
resolves #316

### CODE REVIEW

**Comment by TeddTech** [comment]
> `package-lock.json` file should not be changed in this pull request.

`package-lock.json` changed because I ran `npm i`. I did this to update the dependencies because the build test were not passing.

**Comment by cindyli** [comment]
> > `package-lock.json` file should not be changed in this pull request.
> 
> `package-lock.json` changed because I ran `npm i`. I did this to update the dependencies because the build test were not passing.

OK. Good to know. Did you figure out why the build test passes on the local machine but not for deploy previews?

**Comment by cindyli** [comment]
The build test passes on the other pull request https://github.com/inclusive-design/wecount.inclusivedesign.ca/pull/315 without needing to change `package-lock.json`. Maybe we could try again with an unchange `package-lock.json` in this pull request to see how it goes and what the failure is. What do you think, @TeddTech?

**Comment by TeddTech** [comment]
> The build test passes on the other pull request #315 without needing to change `package-lock.json`. Maybe we could try again with an unchange `package-lock.json` in this pull request to see how it goes and what the failure is. What do you think, @TeddTech?

Okay I'll try it out

**Comment by TeddTech** [comment]
@cindyli It is now working fine without a dependency update

**Pull request merged**
