### PR TITLE
Svg on high contrast

### PR DESCRIPTION
**Pull request by cindyli**
* [X] This pull request has been linted by running `npm run lint` without errors
* [X] This pull request has been tested by running `npm run start` and reviewing affected routes
* [X] This pull request has been built by running `npm run build` without errors
* [X] This isn't a duplicate of an existing pull request

## Description

To resolve https://github.com/inclusive-design/wecount.inclusivedesign.ca/issues/136 and https://github.com/inclusive-design/wecount.inclusivedesign.ca/issues/236

This pull request is based off the pull request for adding UIO (https://github.com/inclusive-design/wecount.inclusivedesign.ca/pull/230), which should be reviewed and merged first.

Use [this link](https://github.com/TeddTech/wecount.inclusivedesign.ca/compare/add-uio...cindyli:svg-on-highContrast) to view the difference between this pull request and [the pull request](https://github.com/inclusive-design/wecount.inclusivedesign.ca/pull/230) it's based off.

## Steps to test

1. Open UIO and select different high contrast themes;
2. SVGs on the header, footer, news and views pages should adapt to high contrast colors.

### CODE REVIEW

**Comment by TeddTech** [comment]
Looks good but appearance may be inverted?

the appearance during hover/focus should be default
and
the appearance during default should be hover/focus

**Comment by cindyli** [comment]
> Looks good but appearance may be inverted?
> 
> the appearance during hover/focus should be default
> and
> the appearance during default should be hover/focus

Can you elaborate the appearance of what? It would be nice if you can use a theme as an example to clarify colors for default and hover/focus. Thanks.

**Comment by TeddTech** [comment]
@cindyli when looking at the social media icons I personally think the colour during hover/focus should be default color instead.

Example:

Screen Shot 2020-05-21 at 2 52 50 PM

The black fill (shown in the facebook icon) should be default and the black outline (shown in twitter and instagram should be hover/focus. Right now it is the other way around.

**Comment by cindyli** [comment]
> @cindyli when looking at the social media icons I personally think the colour during hover/focus should be default color instead.
> 
> Example:
> 
> Screen Shot 2020-05-21 at 2 52 50 PM
> 
> The black fill (shown in the facebook icon) should be default and the black outline (shown in twitter and instagram should be hover/focus. Right now it is the other way around.

@lliskovoi, could you suggest what default and hover/focus styling should look like for social media icons on high contrast. 

Just in case you don't know how to access the deploy preview for this pull request, the link is [here](https://deploy-preview-237--wecount.netlify.app/). 

Thanks.

**Comment by lliskovoi** [comment]
> > @cindyli when looking at the social media icons I personally think the colour during hover/focus should be default color instead.
> > Example:
> > Screen Shot 2020-05-21 at 2 52 50 PM
> > The black fill (shown in the facebook icon) should be default and the black outline (shown in twitter and instagram should be hover/focus. Right now it is the other way around.
> 
> @lliskovoi, could you suggest what default and hover/focus styling should look like for social media icons on high contrast.
> 
> Just in case you don't know how to access the deploy preview for this pull request, the link is [here](https://deploy-preview-237--wecount.netlify.app/).
> 
> Thanks.

I agree with Ted, the solid colour should be the default and the outline in focus :)

**Comment by cindyli** [comment]
Thanks for the suggestion, @TeddTech and @lliskovoi.

The styling for social media icons has been fixed. This pull request is ready for another look.

**Comment by cindyli** [comment]
Good catch, @greatislander. This should have been fixed. 

I noticed different browsers pick up different colors at rendering these links. For example, Firefox applies the parent link color while Chrome applies text color. I'm now using `currentColor` to use whatever the browser picks up.

**Comment by cindyli** [comment]
This pull request is ready for another look.

**Comment by TeddTech** [comment]
@cindyli  Should there be hover/focus styling for the search icon like there is for the social media icons?

**Comment by cindyli** [comment]
> @cindyli Should there be hover/focus styling for the search icon like there is for the social media icons?

If you meant the search icon in the search input box, it serves as a background image indicating the input box is for performing search. It will never gain the focus. I don't think it needs focus/hover styles.

**Pull request merged**
