### PR TITLE
Issue-91: Add dynamic routing to share one single template

### LINKED ISSUE #91: API: generate page routes dynamically
## Is your feature request related to a problem? Please describe.

Right now, each named page from the WordPress backend has a [corresponding route](https://github.com/inclusive-design/wecount.inclusivedesign.ca/tree/master/pages) (`about.vue`, `tools.vue`, `inclusion-challenges.vue` etc). This involves lots of duplication as all of these Vue files are identical.

## Describe the solution you'd like

All pages except for the Home page (index.vue) should share a single template, under `/_page/index.vue`, and the routes should be generated from the WordPress API response for the pages endpoint: https://wecount.inclusivedesign.ca/wp-json/wp/v2/pages

## Describe alternatives you've considered

Not applicable.

## Additional context

Not applicable.

### PR DESCRIPTION
**Pull request by cindyli**
* [X] This pull request has been linted by running `npm run lint` without errors
* [X] This pull request has been tested by running `npm run dev` and reviewing affected routes
* [X] This pull request has been built by running `npm run generate` without errors
* [X] This isn't a duplicate of an existing pull request

## Description
Fixes #91: these routes: /about/, /tools/, /inclusion-challenges/, /our-data/ now shares one single template at `pages/_requestedPath/index.vue`.

## Steps to test

1. Run `npm run dev` to start the website locally at `http://localhost:3000`;
2. Click through links in the navigation section to verify each page.

**Expected behavior:**
All pages behave the same as the master branch.

### CODE REVIEW

**Comment by TeddTech** [comment]
> [CLA assistant check](https://cla-assistant.io/inclusive-design/wecount.inclusivedesign.ca?pullRequest=104)
> Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/inclusive-design/wecount.inclusivedesign.ca?pullRequest=104) before we can accept your contribution.
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/inclusive-design/wecount.inclusivedesign.ca?pullRequest=104) it.

@cindyli you need to sign the CLAassistant agreement

**Comment by cindyli** [comment]
> @greatislander @cindyli I noticed the generate field in the `nuxt.config.js`file was not edited in accordance with changes made in the `pages/` structure.

Good catch, @TeddTech. I wonder what's the benefit of using `generate()` to build a list of static routes, especially when we are handling an unknown number of news and views. Building static routes for all news/views upfront doesn't seem like an efficient way. 

I tried by removing the build of routes for news/views and the website seems working fine.

Please point out what I missed or haven't been aware. Thanks.

**Comment by greatislander** [comment]
@cindyli @TeddTech It doesn't appear to be needed. It seems like Nuxt is generating the pages dynamically from the store, even when the site is generated statically. I just created a test page on the WordPress site (https://wecount.inclusivedesign.ca/test-page/) and it appears on the deploy preview for this branch: https://deploy-preview-104--wecount.netlify.com/test-page

**Comment by cindyli** [comment]
Thanks for the experiment, @greatislander. Seems promising to remove the `routes` config.

@TeddTech, please let us know if you have concerns.

**Comment by TeddTech** [comment]
> @cindyli @TeddTech It doesn't appear to be needed. It seems like Nuxt is generating the pages dynamically from the store, even when the site is generated statically. I just created a test page on the WordPress site (https://wecount.inclusivedesign.ca/test-page/) and it appears on the deploy preview for this branch: https://deploy-preview-104--wecount.netlify.com/test-page

Thanks for pointing this out Ned. I was under the impression we would have to direct data coming from the API to specific pages in `nuxt.config.js`. I see the `asynceData()`  lifecycle method in `pages/_slug/index.vue` is taking care of this.

**Comment by TeddTech** [comment]
> Thanks for the experiment, @greatislander. Seems promising to remove the `routes` config.
> 
> @TeddTech, please let us know if you have concerns.

I agree. I was under the impression that all dynamic pages (files starting with `_ `in `page/`) had to be specified in the routes config. If this is not the case, removing it would be best. This should be tested and a new issue for this created.

Great job Cindy! Everything looks good.

**Comment by jobara** [comment]
> @cindyli @TeddTech It doesn't appear to be needed. It seems like Nuxt is generating the pages dynamically from the store, even when the site is generated statically. I just created a test page on the WordPress site (https://wecount.inclusivedesign.ca/test-page/) and it appears on the deploy preview for this branch: https://deploy-preview-104--wecount.netlify.com/test-page

I believe this is what I was seeing the other day when I was looking into the issues @TeddTech identified with UIO+ working randomly for read mode and table of contents. If you had the "/" at the end it was probably hitting the staticly generated paths while links top ages that didn't end in "/" would hit the dynamic routes that were loaded like a single page app.

**Comment by TeddTech** [comment]
> > @cindyli @TeddTech It doesn't appear to be needed. It seems like Nuxt is generating the pages dynamically from the store, even when the site is generated statically. I just created a test page on the WordPress site (https://wecount.inclusivedesign.ca/test-page/) and it appears on the deploy preview for this branch: https://deploy-preview-104--wecount.netlify.com/test-page
> 
> I believe this is what I was seeing the other day when I was looking into the issues @TeddTech identified with UIO+ working randomly for read mode and table of contents. If you had the "/" at the end it was probably hitting the staticly generated paths while links top ages that didn't end in "/" would hit the dynamic routes that were loaded like a single page app.

Let's discuss this at the We Count check in today

**Pull request merged**
