### PR TITLE
feat: implement the new design for the initiatives page (resolves #433)

### LINKED ISSUE #433: Implement the new layout for the Initiatives page, workshops section
## Is your feature request related to a problem? Please describe.

The workshops section on the Initiatives page has been redesigned as to [the figma](https://www.figma.com/file/0lcLol3X5MmOXackT2YbHJ/WeCount-website?node-id=2937%3A271). The new design needs to be implemented.

### PR DESCRIPTION
**Pull request by cindyli**
* [X] This pull request has been linted by running `npm run lint` without errors
* [X] This pull request has been tested by running `npm run start` and reviewing affected routes
* [X] This pull request has been built by running `npm run build` without errors
* [X] This isn't a duplicate of an existing pull request

## Description

Implement the new design for the Initiatives page. The new design can be found on the [figma](https://www.figma.com/file/0lcLol3X5MmOXackT2YbHJ/WeCount-website?node-id=2976%3A164).

## Steps to test

1. Go to the initiatives page;
2. The page has the layout as the new design;
3. Test with UIO and the page responds correctly.

**Expected behavior:** 

See above.

### CODE REVIEW

**Review by TeddTech — COMMENTED** [review]
Workshop cards have rounded corners when using default theme and do not when using UIO themes. The workshop cards should also have rounded corners when using UIO them.

Screen Shot 2020-11-12 at 3 04 49 PM

Screen Shot 2020-11-12 at 3 04 39 PM

**Review by TeddTech — COMMENTED** [review]
A coloured bar appears when hovering over the workshop card default image when using the default theme.

Screen Shot 2020-11-12 at 2 47 35 PM

**Review by TeddTech — COMMENTED** [review]
The Digging DEEPer workshop card images appear squished and are hard to read.

Screen Shot 2020-11-12 at 7 37 48 AM

**Comment by cindyli** [comment]
> The Digging DEEPer workshop card images appear squished and are hard to read.

This is a data issue and the main reason to separate images used by workshop cards and individual workshop pages. @uttaraghodke will upload these images later on.

All other comments have been addressed. Good catch, @TeddTech. Thanks.

This PR is ready for another review.

**Review by TeddTech — APPROVED** [review]

**Pull request merged**
