### PR TITLE
feat: homepage update

### PR DESCRIPTION
**Pull request by chosww**
* [x] This pull request has been linted by running `npm run lint` without errors
* [x] This pull request has been tested by running `npm run start` and reviewing affected routes
* [x] This pull request has been built by running `npm run build` without errors
* [x] This isn't a duplicate of an existing pull request

## Description

1. Change the landing page video and upload the blue image provided by @uttaraghodke. All a rectangular blue bar on top as in the Figma design.
2. Replace the image used in the yellow card in the landing page.
3. Add SVG filter for images in different UIO themes.

## Steps to test

1. Go to the landing page
2. See the Youtube player is replaced with an image
3. See different filters are applied to the image in different themes of UIO

### CODE REVIEW

**Comment by greatislander** [comment]
@chosww In addition to the changes we discussed, the YouTube embed NPM dependency can be removed if it's no longer used.

**Comment by chosww** [comment]
@greatislander I updated how we render the banner image as we discussed. I used figure shortcode to render image with alt text, please let me know if this approach seems reasonable and I will update preview as well.

**Review by greatislander — CHANGES_REQUESTED** [review]
The outstanding issue here is the size of the image. We can use the Eleventy Image plugin to optimize it at build time.

**Comment by greatislander** [comment]
Here's a demo: https://github.com/inclusive-design/eleventy-image-test

**Review by greatislander — APPROVED** [review]

**Pull request merged**
