### PR TITLE
fix: remove sharepoint field from resources

### PR DESCRIPTION
**Pull request by chosww**
* [x] This pull request has been linted by running `npm run lint` without errors
* [x] This pull request has been tested by running `npm run start` and reviewing affected routes
* [x] This pull request has been built by running `npm run build` without errors
* [x] This isn't a duplicate of an existing pull request

## Description

Remove SharePoint field from resources, as it is not accessible to public.

### check on the public page

1. Go to resources page
2. Find a resource that had sharepoint url field before; example resource title "Accessible Computer Science for K-12 Students with Disabilities"
3. Check that there's no SharePoint URL field

### check on the admin interface

1. Go to Admin page
2. Create a new resource
3. Check that there's no SharePoint field

### CODE REVIEW

**Comment by chosww** [comment]
Hey @cindyli, I tried to remove existing SharePoint field from resource md files, and I wasn't able to do that. Here's what I have tried in .eleventy.js, using eleventyConfig's addCollection method: 

`javascript
collection.getFilteredByGlob("src/collections/resources/*.md").forEach((resource) => {
    const content = fs.readFileSync(resource.inputPath, 'utf8');
    const sharePointFilter = '\bsharePointUrl:\b';
    const filteredContent = content.replace(sharePointFilter, "");
    fs.writeFileSync(resource.inputPath, filteredContent);
});
`
Could we talk about potential solutions on Monday please?

**Comment by cindyli** [comment]
There are a couple of solutions off the top of my head:

1. write a .njk template to read in every resources from its collection then re-render without "sharePointUrl" field
2. a simpler way is to run a `sed` command in the `src/collections/resources` directory via terminal to remove this line directly from every file

We can definitely talk on Monday.

**Comment by cindyli** [comment]
@chosww open terminal, go to directory `src/collections/resources/`, run this command:

`find . -type f -name "*.md" -print0 | while IFS= read -r -d '' file; do sed -i '' '/^sharePointUrl:/d' "$file"; done`

It will loop through all md files in the directory and remove lines that start with "sharePointUrl:". Works pretty well for me.

**Comment by cindyli** [comment]
@chosww I merged the main branch into the dev. The recent changes to resources markdown files in the main conflict with your changes. Could you resolve conflicts? Thanks.

**Comment by chosww** [comment]
> @chosww I merged the main branch into the dev. The recent changes to resources markdown files in the main conflict with your changes. Could you resolve conflicts? Thanks.

Hey Cindy, the conflicts are all from the updated md files, I feel like it would be quicker to start this work off again from the latest dev branch.

**Comment by cindyli** [comment]
> the conflicts are all from the updated md files, I feel like it would be quicker to start this work off again from the latest dev branch.

I agree.

**Comment by cindyli** [comment]
@chosww please let me know before creating a branch off the dev to redo this work. There are more recent changes made into the main branch. We should merge it into the dev branch before you work on this issue. Thanks.

**Comment by cindyli** [comment]
@chosww as you are still struggling with the Netlify credential issue when running git commands. I will take care the pull request for this fix. Don't worry.

**Comment by cindyli** [comment]
Replaced by https://github.com/inclusive-design/wecount.inclusivedesign.ca/pull/1297

**Pull request closed without merging**
